name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    
    - name: Write value to Properties-file
      uses: christian-draeger/write-properties@1.1.0
      with:
        path: './src/main/resources/aws.properties'
        property: |
          'ACCESS_KEY'
          'SECRET_KEY'
          'BUCKET'
        value: |
          '${{secrets.ACCESS_KEY}}'
          '${{secrets.SECRET_KEY}}'
          '${{secrets.BUCKET}}'

    - name: Display aws.properties content
      run: cat aws.properties


    - name: Change wrapper permissions
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3
        

    - name: Bootjar
      run: ./gradlew bootjar  

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Build & Push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/swe304-project3-web:latest
    
